### ISSUE TITLE
Django s4a and axios

### ISSUE THREAD

**Issue by GDTNguyen** [seo4ajax/django-s4a#1]
Hi,

Is it possible to update the repo to handle requests from Axios?

All the best

**Comment by GDTNguyen** [comment]
apologies solved the issue.

**Comment by gildas-lormeau** [comment]
No problem!

**Comment by gildas-lormeau** [comment]
@GDTNguyen For your information, I just updated the code in order to remove the support of the "_escaped_fragment_" query parameter which is [deprecated](https://developers.google.com/search/docs/ajax-crawling/docs/specification) and replace it with [dynamic rendering](https://developers.google.com/search/docs/guides/dynamic-rendering).
